#   ____            _             
# |  _ \          | |            
# | |_) |_ __ ___ | | _____ _ __ 
# |  _ <| '__/ _ \| |/ / _ \ '__|
# | |_) | | | (_) |   <  __/ |   
# |____/|_|  \___/|_|\_\___|_|
# 
# by ellbristiw
# 
# Configuration File
# 
# salesTax : Tax to charge on each sale (Set to 0.0 for no tax)
# 
# taxIsPercentage : Treat salesTax as a percentage (i.e. tax = 10%)
# 
# minimumTaxable : Transactions below this amoutn will not be charged tax (0.0 = charge tax on ALL transactions)
# 
# 
salesTaxCharge: 0.0
taxIsPercentage: false
minimumTaxable: 0.0