#  ____            _             
# |  _ \          | |            
# | |_) |_ __ ___ | | _____ _ __ 
# |  _ <| '__/ _ \| |/ / _ \ '__|
# | |_) | | | (_) |   <  __/ |   
# |____/|_|  \___/|_|\_\___|_|
# 
# by ellbristiw
# 
# Configuration File
# 
# salesTaxRate : Tax to charge on each sale (Set to 0.0 for no tax)
# 
# taxIsPercentage : Treat salesTax as a percentage (i.e. tax = 10%)
# 
# minimumTaxable : Transactions below this amoutn will not be charged tax (0.0 = charge tax on ALL transactions)
# 
# taxOnBuyOrders : Should buy orders be charged tax?
# 
# payTaxToAccounts : Should tax be paid into an economy account?
# 
# taxRecipients : If paying tax to accounts, what accounts shoudl receive it?
#    NOTE : Separate with commas. Tax is split evenly accross listed accounts
#    TIP : Add dummy names to make some of the tax "dissappear"
# 
# maxOrderPerPlayer : Maximum number of orders a player can list (0 = Unlimited)
# 
# vipMaxOrders : Maximum number of orders a VIP player can list
# 
# villagersAreBrokers : Can you right-click villagers to open the global Broker window?
# 
# playersAreBrokers : Can you right-click players to open their personal Broker window?
# 
# 
salesTaxRate: 0.0
taxIsPercentage: false
minimumTaxable: 0.0
taxOnBuyOrders : true
payTaxToAccounts: false
taxRecipients: player1,player2
maxOrdersPerPlayer: 0
vipMaxOrders: 0
villagersAreBrokers: true
playersAreBrokers: true