name: Broker
main: me.ellbristow.broker.Broker
version: 1.6.0
author: ellbristow
database: true
dev-url: http://dev.bukkit.org/server-mods/broker
depend: [Vault]
description: >
             Trade items using an MMO exchange style trade system
commands:
  broker:
    description: Broker command help
permissions:
  broker.*:
    description: Access to all areas of Broker
    children:
      broker.admin: true
      broker.use: true
      broker.buy.*: true
      broker.commands.*: true
      broker.sign.*: true
  broker.admin:
    description: Admin access to broker
    children:
      broker.commands.buy.admincancel: true
      broker.commands.sell.admincancel: true
  broker.use:
    description: Can use the broker
  broker.commands.*:
    description: Can use all broker commands
    children:
      broker.commands.sell.*: true
      broker.commands.buy.*: true
      broker.commands.buy.admincancel: true
      broker.commands.sell.admincancel: true
  broker.commands.sell.*:
    description: Can use all /broker sell commands
    children:
      broker.commands.sell: true
      broker.commands.sell.buyorders: true
      broker.commands.sell.cancel: true
  broker.commands.sell:
    description: Can list items using '/broker sell [args]' command
  broker.commands.sell.buyorders:
    description: Can view Buy Orders using '/broker sell'
  broker.buy.*:
    description: Can use /broker buy and place Buy Orders
    children:
      broker.commands.buy: true
      broker.commands.buy.orders: true
      broker.commands.buy.cancel: true
  broker.commands.buy:
    description: Can use the '/broker buy' commands
  broker.commands.buy.orders:
    description: Can place Buy Orders with '/broker buy'
  broker.commands.buy.cancel:
    description: Can use /broker buy cancel
  broker.commands.buy.admincancel:
    description: Can use /broker buy admincancel
  broker.commands.sell.cancel:
    description: Can use /broker sell cancel
  broker.commands.sell.admincancel:
    description: Can use /broker sell admincancel
  broker.sign.*:
    description: Can create all Broker signs
    children:
      broker.sign: true
      broker.sign.autosell: true
      broker.sign.buyorders: true
      broker.sign.pricecheck: true
      broker.sign.personal: true
      broker.sign.personal.others: true
  broker.sign:
    description: Admin command to allow creation of broker signs
  broker.sign.autosell:
    description: Can make Broker Auto Sell signs
  broker.sign.buyorders:
    description: Can make Broker Buy Orders signs
  broker.sign.pricecheck:
    description: Can make Broker Price Check signs
  broker.sign.pricecheck.update:
    description: Can right-click to update Price Check signs
  broker.sign.personal:
    description: Can make personal Broker signs (own shop)
  broker.sign.personal.others:
    description: Can make personal Broker signs for others
  broker.vip:
    description: Gain VIP access to broker (VIP order max)
    default: false
