name: Broker
main: me.ellbristow.broker.Broker
version: 1.6.0
author: ellbristow
database: true
dev-url: http://dev.bukkit.org/server-mods/broker
depend: [Vault]
description: >
             Trade items using an MMO exchange style trade system
commands:
  broker:
    description: Broker command help
permissions:
  broker.*:
    description: Access to all areas of Broker
    children:
      broker.admin: true
      broker.use: true
      broker.buy.*: true
      broker.commands.sell: true
      broker.commands.cancel: true
      broker.sign: true
      broker.sign.personal: true
      broker.sign.personal.others: true
  broker.admin:
    description: Admin access to broker
  broker.use:
    description: Can use the broker
  broker.commands.sell:
    description: Can use the '/broker sell' commands
  broker.buy.*:
    description: Can use /broker buy and place Buy Orders
    children:
      broker.commands.buy: true
      broker.commands.buy.orders: true
  broker.commands.buy:
    description: Can use the '/broker buy' commands
  broker.commands.buy.orders:
    description: Can place Buy Orders
  broker.commands.cancel:
    description: Can use /broker sell cancel
  broker.sign:
    description: Admin command to allow creation of broker signs
  broker.sign.personal:
    description: Can make personal Broker signs (own shop)
  broker.sign.personal.others:
    description: Can make personal Broker signs for others
  broker.vip:
    description: Gain VIP access to broker (VIP order max)
